// <auto-generated />
using System;
using FieldSales.Api.Directory;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FieldSales.Api.Directory.Migrations
{
    [DbContext(typeof(DirectoryDbContext))]
    partial class DirectoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FieldSales.Api.Coverage.AssignmentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ActorSubject")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("Cause")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("NewAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("NewLevel")
                        .HasColumnType("int");

                    b.Property<string>("NewRepName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("NewRepSubject")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("NewSourceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("NewUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PreviousAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PreviousLevel")
                        .HasColumnType("int");

                    b.Property<string>("PreviousRepName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PreviousRepSubject")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("PreviousSourceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("PreviousUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Sequence"));

                    b.HasKey("Id");

                    b.HasIndex("Sequence")
                        .IsUnique();

                    b.HasIndex("LocationId", "Sequence");

                    b.HasIndex("NewRepSubject", "Sequence");

                    b.HasIndex("OperationId", "LocationId")
                        .IsUnique();

                    b.HasIndex("PreviousRepSubject", "Sequence");

                    b.ToTable("AssignmentHistory", null, t =>
                        {
                            t.HasTrigger("TR_AssignmentHistory_AppendOnly");

                            t.HasCheckConstraint("CK_AssignmentHistory_Change", "[Id] <> '00000000-0000-0000-0000-000000000000'\nAND [OperationId] <> '00000000-0000-0000-0000-000000000000'\nAND [LocationId] <> '00000000-0000-0000-0000-000000000000'\nAND LEN([LocationName]) > 0 AND LEN([ActorSubject]) > 0 AND LEN([ActorName]) > 0\nAND [Cause] IN (0, 1, 2) AND DATEPART(TZOFFSET, [ChangedAt]) = 0\nAND ([PreviousRepSubject] IS NOT NULL OR [NewRepSubject] IS NOT NULL)\nAND ([PreviousRepSubject] IS NULL OR [NewRepSubject] IS NULL OR [PreviousRepSubject] <> [NewRepSubject])");

                            t.HasCheckConstraint("CK_AssignmentHistory_NewOwner", "([NewRepSubject] IS NULL AND [NewRepName] IS NULL AND [NewAssignmentId] IS NULL\n  AND [NewLevel] IS NULL AND [NewUnitId] IS NULL AND [NewSourceName] IS NULL)\nOR\n([NewRepSubject] IS NOT NULL AND LEN([NewRepSubject]) > 0\n  AND [NewRepName] IS NOT NULL AND LEN([NewRepName]) > 0\n  AND [NewAssignmentId] IS NOT NULL AND [NewAssignmentId] <> '00000000-0000-0000-0000-000000000000'\n  AND [NewLevel] IS NOT NULL AND [NewLevel] IN (0, 1, 2, 3)\n  AND [NewUnitId] IS NOT NULL AND [NewUnitId] <> '00000000-0000-0000-0000-000000000000'\n  AND [NewSourceName] IS NOT NULL AND LEN([NewSourceName]) > 0)");

                            t.HasCheckConstraint("CK_AssignmentHistory_PreviousOwner", "([PreviousRepSubject] IS NULL AND [PreviousRepName] IS NULL AND [PreviousAssignmentId] IS NULL\n  AND [PreviousLevel] IS NULL AND [PreviousUnitId] IS NULL AND [PreviousSourceName] IS NULL)\nOR\n([PreviousRepSubject] IS NOT NULL AND LEN([PreviousRepSubject]) > 0\n  AND [PreviousRepName] IS NOT NULL AND LEN([PreviousRepName]) > 0\n  AND [PreviousAssignmentId] IS NOT NULL AND [PreviousAssignmentId] <> '00000000-0000-0000-0000-000000000000'\n  AND [PreviousLevel] IS NOT NULL AND [PreviousLevel] IN (0, 1, 2, 3)\n  AND [PreviousUnitId] IS NOT NULL AND [PreviousUnitId] <> '00000000-0000-0000-0000-000000000000'\n  AND [PreviousSourceName] IS NOT NULL AND LEN([PreviousSourceName]) > 0)");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("FieldSales.Api.Coverage.RepReportingLine", b =>
                {
                    b.Property<string>("RepSubject")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ManagerSubject")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("RepSubject");

                    b.HasIndex("ManagerSubject");

                    b.ToTable("RepReportingLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_RepReportingLines_Subjects", "LEN([RepSubject]) > 0 AND LEN([ManagerSubject]) > 0");
                        });
                });

            modelBuilder.Entity("FieldSales.Api.Coverage.TerritoryAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CountyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RepSubject")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid?>("TownId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CountyId")
                        .IsUnique()
                        .HasFilter("[CountyId] IS NOT NULL");

                    b.HasIndex("LocationId")
                        .IsUnique()
                        .HasFilter("[LocationId] IS NOT NULL");

                    b.HasIndex("RegionId")
                        .IsUnique()
                        .HasFilter("[RegionId] IS NOT NULL");

                    b.HasIndex("RepSubject");

                    b.HasIndex("TownId")
                        .IsUnique()
                        .HasFilter("[TownId] IS NOT NULL");

                    b.ToTable("TerritoryAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_TerritoryAssignments_OneTarget", "(CASE WHEN [RegionId] IS NULL THEN 0 ELSE 1 END\n + CASE WHEN [CountyId] IS NULL THEN 0 ELSE 1 END\n + CASE WHEN [TownId] IS NULL THEN 0 ELSE 1 END\n + CASE WHEN [LocationId] IS NULL THEN 0 ELSE 1 END) = 1\nAND ([RegionId] IS NULL OR [RegionId] <> '00000000-0000-0000-0000-000000000000')\nAND ([CountyId] IS NULL OR [CountyId] <> '00000000-0000-0000-0000-000000000000')\nAND ([TownId] IS NULL OR [TownId] <> '00000000-0000-0000-0000-000000000000')\nAND ([LocationId] IS NULL OR [LocationId] <> '00000000-0000-0000-0000-000000000000')");
                        });
                });

            modelBuilder.Entity("FieldSales.Api.Directory.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContactTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ContactTypeId");

                    b.HasIndex("Name");

                    b.ToTable("Contacts", null, t =>
                        {
                            t.HasTrigger("TR_Contacts_MainStatus");

                            t.HasCheckConstraint("CK_Contacts_Status", "[Status] IN (0,1)");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("FieldSales.Api.Directory.ContactType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ContactTypes", (string)null);
                });

            modelBuilder.Entity("FieldSales.Api.Directory.County", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("RegionId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Counties", (string)null);
                });

            modelBuilder.Entity("FieldSales.Api.Directory.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("FieldSales.Api.Directory.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Eircode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<Guid?>("LocationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<Guid?>("MainContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int?>("PositionPrecision")
                        .HasColumnType("int");

                    b.Property<string>("PositionSourceEircode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("PositionSourceTownId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("PositionedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("RetiredMainContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TownId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("LocationTypeId");

                    b.HasIndex("MainContactId");

                    b.HasIndex("RetiredMainContactId");

                    b.HasIndex("TownId");

                    b.HasIndex("CustomerId", "NormalizedName");

                    b.HasIndex("Id", "MainContactId");

                    b.HasIndex("Id", "RetiredMainContactId");

                    b.ToTable("Locations", null, t =>
                        {
                            t.HasTrigger("TR_Locations_MainGuard");

                            t.HasCheckConstraint("CK_Locations_MainOrRetired", "[MainContactId] IS NULL OR [RetiredMainContactId] IS NULL");

                            t.HasCheckConstraint("CK_Locations_Position", "([Latitude] IS NULL AND [Longitude] IS NULL AND [PositionPrecision] IS NULL\n  AND [PositionSourceTownId] IS NULL AND [PositionSourceEircode] IS NULL AND [PositionedAt] IS NULL)\nOR\n([Latitude] IS NOT NULL AND [Longitude] IS NOT NULL AND [PositionPrecision] IS NOT NULL\n  AND [Latitude] BETWEEN -90 AND 90 AND [Longitude] BETWEEN -180 AND 180\n  AND [PositionedAt] IS NOT NULL AND\n  (([PositionPrecision] = 0 AND [PositionSourceTownId] IS NOT NULL AND [PositionSourceEircode] IS NULL)\n   OR ([PositionPrecision] = 1 AND [PositionSourceTownId] IS NOT NULL\n       AND [PositionSourceEircode] IS NOT NULL AND LEN([PositionSourceEircode]) > 0)\n   OR ([PositionPrecision] = 2 AND [PositionSourceTownId] IS NULL AND [PositionSourceEircode] IS NULL)))");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("FieldSales.Api.Directory.LocationContact", b =>
                {
                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LocationId", "ContactId");

                    b.HasIndex("ContactId");

                    b.ToTable("LocationContacts", null, t =>
                        {
                            t.HasTrigger("TR_LocationContacts_FirstMain");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("FieldSales.Api.Directory.LocationPositionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<DateTimeOffset>("PositionedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Precision")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ReplacedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SourceEircode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("SourceTownId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "ReplacedAt");

                    b.ToTable("LocationPositionHistory", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocationPositionHistory_Position", "[Latitude] BETWEEN -90 AND 90 AND [Longitude] BETWEEN -180 AND 180 AND\n(([Precision] = 0 AND [SourceTownId] IS NOT NULL AND [SourceEircode] IS NULL)\n OR ([Precision] = 1 AND [SourceTownId] IS NOT NULL AND [SourceEircode] IS NOT NULL AND LEN([SourceEircode]) > 0)\n OR ([Precision] = 2 AND [SourceTownId] IS NULL AND [SourceEircode] IS NULL))");
                        });
                });

            modelBuilder.Entity("FieldSales.Api.Directory.LocationType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LocationTypes", (string)null);
                });

            modelBuilder.Entity("FieldSales.Api.Directory.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("FieldSales.Api.Directory.Town", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CountyId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Towns", null, t =>
                        {
                            t.HasCheckConstraint("CK_Towns_Coordinates", "([Latitude] IS NULL AND [Longitude] IS NULL) OR\n([Latitude] IS NOT NULL AND [Longitude] IS NOT NULL\n  AND [Latitude] BETWEEN -90 AND 90 AND [Longitude] BETWEEN -180 AND 180)");
                        });
                });

            modelBuilder.Entity("FieldSales.Api.Coverage.AssignmentHistory", b =>
                {
                    b.HasOne("FieldSales.Api.Directory.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldSales.Api.Coverage.TerritoryAssignment", b =>
                {
                    b.HasOne("FieldSales.Api.Directory.County", null)
                        .WithMany()
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FieldSales.Api.Directory.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FieldSales.Api.Directory.Region", null)
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FieldSales.Api.Coverage.RepReportingLine", null)
                        .WithMany()
                        .HasForeignKey("RepSubject")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FieldSales.Api.Directory.Town", null)
                        .WithMany()
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FieldSales.Api.Directory.Contact", b =>
                {
                    b.HasOne("FieldSales.Api.Directory.ContactType", null)
                        .WithMany()
                        .HasForeignKey("ContactTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldSales.Api.Directory.County", b =>
                {
                    b.HasOne("FieldSales.Api.Directory.Region", null)
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldSales.Api.Directory.Location", b =>
                {
                    b.HasOne("FieldSales.Api.Directory.Customer", null)
                        .WithMany("Locations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FieldSales.Api.Directory.LocationType", null)
                        .WithMany()
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FieldSales.Api.Directory.Town", null)
                        .WithMany()
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FieldSales.Api.Directory.LocationContact", null)
                        .WithMany()
                        .HasForeignKey("Id", "MainContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Locations_MainContactLink");

                    b.HasOne("FieldSales.Api.Directory.LocationContact", null)
                        .WithMany()
                        .HasForeignKey("Id", "RetiredMainContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Locations_RetiredMainContactLink");
                });

            modelBuilder.Entity("FieldSales.Api.Directory.LocationContact", b =>
                {
                    b.HasOne("FieldSales.Api.Directory.Contact", "Contact")
                        .WithMany("Locations")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FieldSales.Api.Directory.Location", "Location")
                        .WithMany("Contacts")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FieldSales.Api.Directory.LocationPositionHistory", b =>
                {
                    b.HasOne("FieldSales.Api.Directory.Location", null)
                        .WithMany("PositionHistory")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldSales.Api.Directory.Town", b =>
                {
                    b.HasOne("FieldSales.Api.Directory.County", null)
                        .WithMany()
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldSales.Api.Directory.Contact", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("FieldSales.Api.Directory.Customer", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("FieldSales.Api.Directory.Location", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("PositionHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
