// <auto-generated />
using System;
using FieldSales.Api.Catalogue;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FieldSales.Api.Catalogue.Migrations
{
    [DbContext(typeof(CatalogueDbContext))]
    [Migration("20260930173447_AddMinimumProducts")]
    partial class AddMinimumProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FieldSales.Api.Catalogue.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Categories_RootName")
                        .HasFilter("[ParentId] IS NULL");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Categories_SiblingName")
                        .HasFilter("[ParentId] IS NOT NULL");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("FieldSales.Api.Catalogue.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ParentProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_Code");

                    b.HasIndex("ParentProductId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("FieldSales.Api.Catalogue.ProductBasePrice", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId", "EffectiveFrom");

                    b.ToTable("ProductBasePrices", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductBasePrices_NonNegativeAmount", "[Amount] >= 0");
                        });
                });

            modelBuilder.Entity("FieldSales.Api.Catalogue.Category", b =>
                {
                    b.HasOne("FieldSales.Api.Catalogue.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FieldSales.Api.Catalogue.Product", b =>
                {
                    b.HasOne("FieldSales.Api.Catalogue.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FieldSales.Api.Catalogue.Product", null)
                        .WithMany()
                        .HasForeignKey("ParentProductId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FieldSales.Api.Catalogue.ProductBasePrice", b =>
                {
                    b.HasOne("FieldSales.Api.Catalogue.Product", null)
                        .WithMany("BasePrices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldSales.Api.Catalogue.Product", b =>
                {
                    b.Navigation("BasePrices");
                });
#pragma warning restore 612, 618
        }
    }
}
